title: Lyric 的二次元主页
page-top-title: Lyric
top-section-bg-text: Welcome to My ACG World
home-subtitle: Lyric&ensp;|&ensp;二次元开发者
articles-subtitle: <i class="bi bi-journal-richtext"></i> 文章
achievements-subtitle: <i class="bi bi-stars"></i> 成就
share-subtitle: <i class="bi bi-chat-square-heart"></i> 分享
links-subtitle: <i class="bi bi-link-45deg"></i> 友链
copyright-text: '&copy; Lyric 2023-2026. All Rights Reserved.'
